# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internet_store', '0002_postad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('CourierId', models.AutoField(primary_key=True, serialize=False)),
                ('CourierName', models.CharField(max_length=200)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internet_store.User')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('DeliveryId', models.AutoField(primary_key=True, serialize=False)),
                ('DeliveryOrderDateTime', models.DateTimeField(auto_now_add=True)),
                ('DeliveryCompleteDateTime', models.DateTimeField()),
                ('ProductAmount', models.PositiveIntegerField()),
                ('OrderTotalSum', models.DecimalField(decimal_places=2, max_digits=30)),
                ('House', models.PositiveIntegerField()),
                ('Building', models.PositiveIntegerField()),
                ('CourierId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internet_store.Courier')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingSource',
            fields=[
                ('MarketingSourceId', models.AutoField(primary_key=True, serialize=False)),
                ('MarketingSourceName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=200)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('ProductTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductTypeName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('RegionId', models.AutoField(primary_key=True, serialize=False)),
                ('RegionName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('StreetId', models.AutoField(primary_key=True, serialize=False)),
                ('StreetName', models.CharField(max_length=200)),
                ('RegionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internet_store.Region')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ProductTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internet_store.ProductType'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='MarketingSourceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internet_store.MarketingSource'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='ProductId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internet_store.Product'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='StreetId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internet_store.Street'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internet_store.User'),
        ),
    ]
