# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_store', '0003_auto_20160425_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
