# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet_store', '0004_auto_20160502_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostAd',
        ),
    ]
