# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_store', '0005_delete_postad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='CourierName',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
