# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_store', '0006_auto_20160516_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingsource',
            name='MarketingSourceName',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductName',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='ProductTypeName',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='RegionName',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='street',
            name='StreetName',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
