# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_store', '0007_auto_20160517_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingsource',
            name='MarketingSourceName',
            field=models.CharField(max_length=200),
        ),
    ]
