# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_store', '0008_auto_20160517_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingsource',
            name='MarketingSourceName',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
