# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internet_store', '0009_auto_20160518_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='ProductType',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='internet_store.ProductType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='Region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='internet_store.Region'),
            preserve_default=False,
        ),
    ]
