# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet_store', '0010_auto_20160520_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='ProductType',
            new_name='ProductTypeId',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='Region',
            new_name='RegionId',
        ),
    ]
