# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_store', '0011_auto_20160520_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alco',
            fields=[
                ('AlcoId', models.AutoField(primary_key=True, serialize=False)),
                ('AlcoName', models.CharField(max_length=200)),
                ('AlcoVolume', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
