# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_store', '0012_alco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alco',
            name='AlcoVolume',
            field=models.IntegerField(),
        ),
    ]
