# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet_store', '0013_auto_20160523_2235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alco',
        ),
    ]
